### PR TITLE
Don't show keyboard on widget init

### LINKED ISSUE #13: autofocus does not seem to work
I have an `ChipsInput` within a scrollable `Column` and as soon as the ChipsInput comes into view the keyboard pops up.  I've tried to set `autofocus` to `false` but it doesn't seem to have any effect

This is on Flutter 3.10.0

### PR DESCRIPTION
**Pull request by BurningAXE**
Fixes #13

### CODE REVIEW

**Comment by mark8044** [comment]
@BurningAXE @nlfiedler Awesome thanks guys!   FYI, this isn't showing up on pub.dev

**Comment by nlfiedler** [comment]
The fix needs testing before publishing. If you have tried it and resolves the issue, please let me know. Thanks.

**Comment by nlfiedler** [comment]
The fix introduced a comparatively more troublesome issue (bug #18) so I am reluctant to make a release until that can be fixed, otherwise we're just shifting one minor issue into another really annoying issue.

**Comment by mark8044** [comment]
> The fix introduced a comparatively more troublesome issue (bug #18) so I am reluctant to make a release until that can be fixed, otherwise we're just shifting one minor issue into another really annoying issue.

You are right, never even noticed that.  Bad bug.  Needs to be reverted

**Pull request merged**
